# Generated by Django 3.0.5 on 2021-04-30 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальное название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Жанр')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальное название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название произведения')),
                ('year', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Год публикации')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='titles', to='title.Categories', verbose_name='Категория')),
                ('genre', models.ManyToManyField(blank=True, related_name='titles', to='title.Genres', verbose_name='Жанр')),
            ],
        ),
    ]
